Repository CICBA/DSpace, pull requests merged in 2020-03, with the labels that each got.

#39 -#5650 Ahora en las páginas de comunidades y colecciones las estadísicas de acceso se muestran considerando solo los accesos acumulados a los items pertenecientes a esa comunidad/coleccion
  dspace-api/src/main/java/org/dspace/statistics/content/DatasetGenerator.java
  dspace-api/src/main/java/org/dspace/statistics/content/StatisticsDataVisits.java
  dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/statistics/StatisticsTransformer.java
Labels: statistics

#40 -#5687 Ahora se hace un commit luego de procesar cada objecto cuando se setea el scope="object" en una tarea de curation
  dspace-api/src/main/java/org/dspace/curate/Curator.java
Labels: CLI

#41 -#5065 Se agregaron configuraciones propias en archivo local_custom.cfg
  dspace/config/dspace.cfg
  dspace/config/local_custom.cfg
Labels: configuration

#43 -#5666 Limpiar expresiones regulares en los archivos de userAgent
  dspace/config/spiders/agents/COUNTER_Robots_list.txt
  dspace/config/spiders/agents/example
  dspace/config/spiders/agents/iplists.com-non_engines
  dspace/config/spiders/agents/sedici_useragents
Labels: statistics

#45 Agrego buscadores en los selects de colecciones usando select2
  dspace/modules/xmlui/src/main/webapp/themes/cicba/css/select2.min.css
  dspace/modules/xmlui/src/main/webapp/themes/cicba/css/style-cicba.css
  dspace/modules/xmlui/src/main/webapp/themes/cicba/js/select2.min.js
  dspace/modules/xmlui/src/main/webapp/themes/cicba/lib/xsl/core/page-structure.xsl
  dspace/modules/xmlui/src/main/webapp/themes/cicba/sitemap.xmap
Labels: xmlui
